### ISSUE TITLE
Global Buttons Not Getting Added to the Personal File

### ISSUE THREAD

**Issue by jayrajput** [rswgnu/hyperbole#163]
I have setup the variable (hbmap:dir-user) for the personal file. But the Global buttons are not getting added to it. The document says that the global buttons will be appended to the personal file. I have also verified that if I open the personal file using the hyperbole menu, it goes to the ~/org/HYPB.

```
  #+begin_src elisp
    (global-set-key (kbd "C-x C-h") 'hkey-either)
    (setq hbmap:dir-user "~/org")
    (unless (and (featurep 'hyperbole) hyperbole-mode)
      (when (< emacs-major-version 27)
        (error "Hyperbole requires Emacs 27 or above; you are running version %d" emacs-major-version))
      (push "~/git/hyperbole" load-path)
      (require 'hyperbole)
      (hyperbole-mode 1))
  #+end_src
```

**Comment by rswgnu** [comment]
Hi Jay:

You are correct and we know the source of the problem and have applied a fix for the next git push.  Look for it tomorrow and then restart your Emacs and things should work as you want.  Thanks for pointing this out.

**Comment by jayrajput** [comment]
Thanks. Working fine for me now. I will suggest that when appending the Global Buttons to the personal file, a comment suggesting that these are you global buttons added by Hyperbole. 

Also I see that the actual button code is maintained in the .hypb file. Can I edit that file manually? I like the flexibility of editing the file rather than the menu. I feel menu is useful when you are learning. But once you get a hang of it, editing the file itself in emacs is faster. So need both.

Also since we are at it, why not completely remove the .hypb file and just store the code/data in the personal butfile. It is elisp anyway and all emacs user has some understanding of elisp. It can be something similar to the custom-set-variables and custom-set-faces added by Custom to the .emacs.

**Comment by rswgnu** [comment]
On Sat, Feb 5, 2022 at 10:04 PM Jay Rajput ***@***.***> wrote:

> Thanks. Working fine for me now.
>
Great.

> I will suggest that when appending the Global Buttons to the personal
> file, a comment suggesting that these are you global buttons added by
> Hyperbole.
>
No, any named button in that file can be used as a global button, whether
created as a regular explicit or named implicit button or through the
global button creation UI, so there should not be any separation of the
buttons in this file.
Note that this is a text files with buttons in it, not an Elisp file, as we
will discuss below.

> Also I see that the actual button code is maintained in the .hypb file.
> Can I edit that file manually?
>
Yes, if you like and are careful.  Button data is read each time the button
is activated.

> I like the flexibility of editing the file rather than the menu. I feel
> menu is useful when you are learning. But once you get a hang of it,
> editing the file itself in emacs is faster. So need both.
>
Okay.

> Also since we are at it, why not completely remove the .hypb file and just
> store the code/data in the personal butfile. It is elisp anyway and all
> emacs user has some understanding of elisp. It can be something similar to
> the custom-set-variables and custom-set-faces added by Custom to the .emacs.
>
The core of Hyperbole is embedding flexible hyperbuttons in textual and
multi-language programming files (within comments).  We don't want to see
or use heavy markup nor do we want to see a lot of code like people embed
within Org files.
I personally almost never look at the .hypb files and instead annotate my
buttons with surrounding text if I want any more information.  That said,
we have started to allow non-file buffers to store button data hidden at
the end of their buffers, just as is done in mail/message and news edit
buffers.  So eventually we may allow this for buffers with files attached
but the button data would still be hidden at the end of the buffer.  If you
want to see button data, you use {C-h A} with point on the button to see it
in a nicely formatted form.

Please join the Hyperbole mail list with {C-h h m j C-c C-c} and lets move
further discussion there so others can benefit.

Regards,

Bob

**Comment by jayrajput** [comment]
Thanks for the response. Make sense to me.
