### ISSUE TITLE
Resolve Koutline klinks on html export

### ISSUE THREAD

**Issue by circius** [rswgnu/hyperbole#2]
Koutline is so far as I know the only software which provides automatic legal numbering within emacs (see [this](https://stackoverflow.com/questions/31948231/how-to-create-a-multi-level-ordered-numbered-plain-list-in-org-mode) unhappy question on stackexchange.) That is extremely useful functionality; and the ability to dynamically cross-reference nodes (thanks to the UID / outline-number distinction) makes it very valuable indeed.

However, hyperbole's limited export functionality restricts the utility of this function for preparing non-digital documents.

The principal problem is not the limited range of export _formats_ - html is good enough - but that kexport:html leaves klinks unaltered. That's good enough (though imperfect) for an HTML document, but it introduces considerable friction on the path to plain-text, latex etc.

Current behaviour: klinks of the form  `<@ 3b=06>` are transformed on export to HTML into links of the form `<a href="#06"><@ 3b=06></a>`.

Desired behaviour: that an option be implemented whereby klinks of the form `<@ 3b=06>` be transformed to a link of the form  `<a href="#06">3b</a>`.

That should allow reasonably straightforward post-processing. Of course I can do this at the moment with helper scripts, but I think this change would be useful for everyone.

Ideal behaviour would probably be an option to export to a nicely-formatted org-buffer with org-links, so that org-export could be utilised directly.

**Comment by rswgnu** [comment]
> Koutline is so far as I know the only software which provides automatic legal numbering within emacs (see [this](https://stackoverflow.com/questions/31948231/how-to-create-a-multi-level-ordered-numbered-plain-list-in-org-mode) unhappy question on stackexchange.) That is extremely useful functionality; and the ability to dynamically cross-reference nodes (thanks to the UID / outline-number distinction) makes it very valuable indeed.

Great.  Maybe you could point them to Hyperbole on StackOverflow even though that is an old question.

> However, hyperbole's limited export functionality restricts the utility of this function for preparing non-digital documents. The principal problem is not the limited range of export _formats_ - html is good enough - but that kexport:html leaves klinks unaltered. That's good enough (though imperfect) for an HTML document, but it introduces considerable friction on the path to plain-text, latex etc.

Maybe you could explain what the friction is in some detail.  Is it that the '@' symbol is left in and conflicts with other formatting you want or is it the permanent id?

> Current behaviour: klinks of the form  `<@ 3b=06>` are transformed on export to HTML into links of the form `<a href="#06"><@ 3b=06></a>`.
 
> Desired behaviour: that an option be implemented whereby klinks of the form `<@ 3b=06>` be transformed to a link of the form  `<a href="#06">3b</a>`.

I see how you might want the simpler hyperlink text in many cases, however, that fails in cases where you are documenting the Koutliner itself and want to explain the link format itself such as these paragraphs where the text won't make much sense if it leaves out the klink format:

       3c1a. <@ 3b=06> jumps to the cell within this outline which has
              permanent id `06' and relative id `3b'.  <@ 06> does the same
              thing, as does <@ 2b>, though this latter form will not
              maintain the link properly if the cell is moved elsewhere
              within the outline.

        3c1b. <EXAMPLE.kotl, 4=012 |c1e> displays the named file, starting at
              the unimplemented features section whose permanent identifer is
              012, with the view specification of: blank lines turned off,
              cutoff after one line per cell, and show ellipses for cells or
              trees which are clipped.

I am open to ideas on how both cases could be supported via some option that would not get in the way of exporting multiple files in batch mode.

For your own brute force fix, simply change the formatting used in the short function, kexport:html-file-klink, found in "${hyperb:dir}/kotl/kexport.el."

> Ideal behaviour would probably be an option to export to a nicely-formatted org-buffer with org-links, so that org-export could be utilised directly.

I think that is a good idea as well.  We will add it to the Hyperbole todo list.  Thank you.

**Comment by circius** [comment]
> Great. Maybe you could point them to Hyperbole on StackOverflow even though that is an old question.
Done.

>Maybe you could explain what the friction is in some detail. Is it that the '@' symbol is left in and conflicts >with other formatting you want or is it the permanent id?

It's a significant strength of koutline that it provides both an absolute and a hierarchy-relative ID for its cells; but on export the practical difference between the two becomes, as far as I can see, void, and the absolute ID (and associated syntax) becomes redundant information.

So in every use-case I can conceive of *for myself* I would prefer klinks to resolve into simple references to cells by hierarchical position. The "friction" I mentioned consists in performing this replacement programmatically after running kexport-html.

I agree this isn't a bug! since all the information is there, in the right place. But I think the kind of export I'm talking about would be widely-enough used to warrant its implementation as a feature.

>I am open to ideas on how both cases could be supported via some option that would not get in the way of >exporting multiple files in batch mode.

>For your own brute force fix, simply change the formatting used in the short function, kexport:html-file-klink, >found in "${hyperb:dir}/kotl/kexport.el."

I'm still pretty new to emacs - so perhaps the suggestion is bad style - but perhaps one could just replace the relevant string in kexport if kexport:html were called with a prefix?

Anyway, I'll make the "brute-force fix" you suggest. Thank you again for this useful software.

**Comment by rswgnu** [comment]
For completeness before closing this issue, note that `kexport:html` already uses a prefix argument to disable use of hard newlines (fixed line ending widths) when exportking kcells to html, so that is not available as an option.  I have decided to leave this as-is and allow people who really need such functionality to manually change it.  Since relative links can be embedded in Koutlines already, when an absolute link is added, one more than likely wants that in the export as well.
