### ISSUE TITLE
hypb:function-copy: (hypb:function-copy): ‘quit-window’ is a primitive; can’t copy body

### ISSUE THREAD

**Issue by alex-a-soto** [rswgnu/hyperbole#27]
Greetings, 

Thank you for creating Hyperbole, in the past I've been able to use Hyperbole, I recently updated emacs to the latest version using the native-comp branch and now I'm unable to start Hyperbole.

Thank you for your time and support.

**Bug Description**
Unable to start Hyperbole, the following error is displayed.

`
hypb:function-copy: (hypb:function-copy): ‘quit-window’ is a primitive; can’t copy body
`

Used emacs -Q to start emacs.

**Version**
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.17.3) of 2020-05-12

Native-Comp Branch

**Comment by matsl** [comment]
Hi Alex,

I tried to recreate this problem but with no luck I'm afraid. 
`GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2020-05-17

Emacs: 9e9421c7ee (feature/native-comp origin/feature/native-comp * Fix bug#41346 assertion triggered while loading dump)
Hyperbole: c050a69c6 (kotl/klink.el: (require 'kcell): Removed recursive require loop) 
(Byte-compiled with the version of emacs above)
`
I use this for initializing Hyperbole after starting with emacs -Q:
`;; Hyperbole
(add-to-list 'load-path "~/src/hyperbole")
(load "hyperbole-autoloads")
(hyperbole-toggle-messaging 1)
(load "hversion")
`

**Comment by alex-a-soto** [comment]
matsl, Thank you for trying to recreate the problem. 

I'm using this [AUR package](https://aur.archlinux.org/packages/emacs-native-comp-git) to install emacs-native-comp version. 

I'm going to re-install the native-comp version from git and see if any changes made recently to the feature/native-comp branch address the issue.

Thank you.

**Comment by rswgnu** [comment]
Native-comp is replacing the Lisp code with binary, right? So when Hyperbole tries to replace the body of that function, it fails because it is essentially a primitive.  We haven’t considered this simce it is highly experimental right now but maybe a workaround could be developed.  Thanks for pointing it out.

-- Bob

**Comment by alex-a-soto** [comment]
@rswgnu Thank you for the insight and glad to help out. In the end, I decided to go back and install Emacs 26.3. I'll try out Emacs 28.0.50 in the future once it stabilizes.

**Comment by rswgnu** [comment]
A pull of the latest master from here should have resolved this issue.  We are not handling when quit-window is a primitive (non-Lisp code).
