### ISSUE TITLE
Donating to Hyperbole?

### ISSUE THREAD

**Issue by alex-a-soto** [rswgnu/hyperbole#29]
Hello,

I was wondering if it would be possible to donate to the hyperbole project? I remember in the past there was a link to [saythanks](https://saythanks.io/), and it seems like that doesn't work anymore?

Thank you!

**Comment by rswgnu** [comment]
Thanks, Alex.  Yes, the saythanks service was taken offline so we had to remove that.  For donations, we would suggest donating to the FSF and mentioning GNU Hyperbole as a motivation.  We very much appreciate the sentiment.
