### ISSUE TITLE
Issue with hyperbole and web mode

### ISSUE THREAD

**Issue by williamchanter** [rswgnu/hyperbole#3]
Hi, I think this is the right place to post this, 

I've been having an issue here https://github.com/syl20bnr/spacemacs/issues/10724 and it seems to have come down to maybe being a `hyperbole` issue. 

Seems more specifically an issue with `web-mode-hook` as talked about here https://github.com/syl20bnr/spacemacs/issues/10724#issuecomment-391717839 

The outcome is with `hyperbole` installed this happens when looking at code in `web-mode` ...

![Picture of issue on Imgur](http://i.imgur.com/aGnl5sk.png)

This may also in part be related to `smartparens` as mentioned in the issue above. https://github.com/syl20bnr/spacemacs/issues/10724#issuecomment-391668701 

Thanks for any help with this, I've found `hyperbole` is great just found this slight bug which I can't seem to fix

Thanks

**Comment by rswgnu** [comment]
I believe we discussed this elsewhere,  maybe on reddit, and that the issue was with smartparens.  Did you get this resolved.  If not, could you describe what you think Hyperbole is doing that causes you the problem.  Thanks.
