### ISSUE TITLE
Instructions for installing with elpaca package manager? (void-variable hyperbole-run-test)

### ISSUE THREAD

**Issue by matogoro** [rswgnu/hyperbole#367]
I've recently migrated from `straight.el` to `elpaca`, and unfortunately this broke my `hyperbole` installation.  I originally had `hyperbole` installed using the guide provided by the manual [here](https://www.gnu.org/software/hyperbole/man/hyperbole.html#Git-In_002dDevelopment-Package-Installation)---I've largely tried to reproduce this in `elpaca` but I keep getting the following error when my config tries to load `hypb-ert.el`:

`Eager macro-expansion failure: (void-variable hyperbole-run-test)`

I feel that I'm most of the way there, but I'm just missing something basic.  What I've done so far:

- clone hyperbole from the source repo ("https://git.savannah.gnu.org/git/hyperbole.git")
- manually symlink the `/kotl`, `/man`, and `/test` folders from the `/elpaca/repos/hyperbole` directory to the `/elpaca/builds/hyperbole` directory

I'd greatly appreciate if anyone here has any insight, but also please let me know if my question is better asked over at `elpaca`.  Thanks!

**Comment by fabinhorsff** [comment]
I am getting the same error. But my config is a little different. I am running Doom Emacs.

* (package! hyperbole) is properly pulling Hyperbole from the repos.
* Any mention of (use-package! hyperbole) or (after! hyperbole) in the config.el works in the first start, and then ceases o work after the second restart. If (hyperbole-mode 1) is called from config.el starts emacs on a scratch mode and freeze. 

Attempts to run it manually (Mx hyperbole-mode) also generate the same error as mentioned above (but does not crash emacs). Only generates the (void-variable hyperbole-run-test)

The only way I found to make it work again e to delete the module from ~.config/emacs/modules (either manually or by removing.  (package! hyperbole) and "doom sync" (as is the instruction with Doom emacs).

It will work again with no errors. This error began after one of the upgrades.

**Comment by rswgnu** [comment]
We’ll look at this and try to resolve it tonight.  I am sure it’s some kind of simple dependency relation that needs fixing (and a test case!).  Thanks for reporting it.-- rswOn Jul 16, 2023, at 12:18 PM, fabinhorsff ***@***.***> wrote:﻿
I am getting the same error. But my config is a little different. I am running Doom Emacs.

(package! hyperbole) is properly pulling Hyperbole from the repos.
Any mention of (use-package! hyperbole) or (after! hyperbole) in the config.el works in the first start, and then ceases o work after the second restart. If (hyperbole-mode 1) is called from config.el starts emacs on a scratch mode and freeze.

Attempts to run it manually (Mx hyperbole-mode) also generate the same error as mentioned above (but does not crash emacs). Only generates the (void-variable hyperbole-run-test)
The only way I found to make it work again e to delete the module from ~.config/emacs/modules (either manually or by removing.  (package! hyperbole) and "doom sync" (as is the instruction with Doom emacs).
It will work again with no errors. This error began after one of the upgrades.

**Comment by rswgnu** [comment]
Latest merge to master should fix this compilation error.  Let us know whether that is so and we can close this.

**Comment by fabinhorsff** [comment]
Almost! No crash, but a different error.

When I try to load Mx hyperbole-mode I get 

`hyperb:generate-autoloads: Hyperbole failed to generate autoload files; try running ’make src’ in a shell in /Users/rsff/.config/emacs/.local/straight/build-28.2/hyperbole/
`

I have not to tried to add hyperbole to my config.el. I figured that if it works with Mx, then it should work in my doom´s config.el.

**Comment by fabinhorsff** [comment]
Looking a little further, I got the following information from the async buffer, after an attempted re-install:

This was from the async native compile log. I hope it helps.

```
Compiling /Users/rsff/.config/emacs/.local/straight/build-28.2/hyperbole/set.el...
ld: warning: -undefined dynamic_lookup may not work with chained fixups
Compiling /Users/rsff/.config/emacs/.local/straight/build-28.2/hyperbole/hact.el...

In end of data:
hact.el:518:31: Warning: the function ‘hattr:list’ is not known to be defined.
hact.el:523:25: Warning: the function ‘hattr:get’ is not known to be defined.
hact.el:514:20: Warning: the function ‘hbut:is-p’ is not known to be defined.
hact.el:398:24: Warning: the function ‘hpath:absolute-arguments’ is not known to be defined.
hact.el:376:4: Warning: the function ‘hattr:set’ is not known to be defined.
hact.el:204:19: Warning: the function ‘hypb:indirect-function’ is not known to be defined.
ld: warning: -undefined dynamic_lookup may not work with chained fixups
Compilation finished.
```

**Comment by fabinhorsff** [comment]
I got it working! 

I had to manually symlink kotl/, man/ and test/ directories from repos/ to build.28-2 on  ~/.config/emacs/.local/straight/

I hope I´m in the right direction!

**Comment by matogoro** [comment]
I'll add in that there have been fixes implemented on the `elpaca` side of things to get this working as well.  Please see [this issue](https://github.com/progfolio/elpaca/issues/162).

With the newest version of `elpaca` and my (vanilla) Emacs, this now works seamlessly with the following `use-package` declaration in my config:

`(use-package hyperbole :elpaca (:files ("*" "man/*" (:exclude "man"))))`

Thank you all for your help, and hopefully this is useful!

**Comment by rswgnu** [comment]
Great, thanks for figuring it out.  We’ll have to add the elpaca recipe.-- rswOn Jul 17, 2023, at 8:27 PM, matogoro ***@***.***> wrote:﻿
I'll add in that there have been fixes implemented on the elpaca side of things to get this working as well.  Please see this issue.
With the newest version of elpaca and my (vanilla) Emacs, this now works seamlessly with the following use-package declaration in my config:
(use-package hyperbole :elpaca (:files ("*" "man/*" (:exclude "man"))))
Thank you all for your help, and hopefully this is useful!

**Comment by wereket** [comment]
> elpaca
in my config I have
(use-package hyperbole :elpaca (:files ("*" "man/*" (:exclude "man"))))

I cloned the repo inside ~/.emacs.d/site-elisp/hyperbole

I get config error hyperbole, void-function vertico-mouse-mode

**Comment by rswgnu** [comment]
Try again with the latest github pre-release; this should fix it.

**Comment by rswgnu** [comment]
Seems to be fixed, closing this.
