### ISSUE TITLE
Readonly Buffer for creation of Global Buttons?

### ISSUE THREAD

**Issue by fabinhorsff** [rswgnu/hyperbole#370]
I´m trying to create a global button and I am getting the following error:

```
Debugger entered--Lisp error: (error "(gbut-create) Read-only error in Hyperbole button buffer ’HYPB’.  Use {SPC t r} to enable edits.")
  error("(gbut-create) Read-only error in Hyperbole button buffer 'HYPB'.  Use {SPC t r} to enable edits.")
  hypb:error("(gbut-create) Read-only error in Hyperbole button buffer 'HYPB'.  Use {SPC t r} to enable edits.")
  (progn (pop-to-buffer but-buf) (hypb:error err))
  (if err (progn (pop-to-buffer but-buf) (hypb:error err)))
  (let (err) (save-current-buffer (set-buffer but-buf) (if buffer-read-only (progn (setq err (format "(%s) Read-only error in Hyperbole button buffer '%s'.  Use {%s} to enable edits." func-name (buffer-name but-buf) (hmouse-read-only-toggle-key)))))) (if err (progn (pop-to-buffer but-buf) (hypb:error err))))
  hui:buf-writable-err(#<buffer HYPB> "gbut-create")
  (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action (progn (hui:action actype)))) (set-buffer but-buf) (setq lbl (concat lbl (ebut:operate lbl nil))) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl))
  (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action (progn (hui:action actype)))) (set-buffer but-buf) (setq lbl (concat lbl (ebut:operate lbl nil))) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl)))
  (if ibut-flag (hui:gibut-create lbl (hui:hbut-label nil "gbut-create" "Implicit button text (with any delimiters): ")) (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action (progn (hui:action actype)))) (set-buffer but-buf) (setq lbl (concat lbl (ebut:operate lbl nil))) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl))))
  (progn (if ibut-flag (hui:gibut-create lbl (hui:hbut-label nil "gbut-create" "Implicit button text (with any delimiters): ")) (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action (progn ...))) (set-buffer but-buf) (setq lbl (concat lbl (ebut:operate lbl nil))) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl)))))
  (unwind-protect (progn (if ibut-flag (hui:gibut-create lbl (hui:hbut-label nil "gbut-create" "Implicit button text (with any delimiters): ")) (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action ...)) (set-buffer but-buf) (setq lbl (concat lbl ...)) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl))))) (if (eq start-buffer (current-buffer)) nil (error "Start buffer, '%s', differs from end buffer, '%s'" start-buffer (current-buffer))) (if (buffer-live-p start-buffer) nil (error "End buffer, '%s', is not live" (current-buffer))))
  (let ((debug-on-error t) (start-buffer (current-buffer))) (if (buffer-live-p start-buffer) nil (error "Start buffer, '%s', is not live" (current-buffer))) (unwind-protect (progn (if ibut-flag (hui:gibut-create lbl (hui:hbut-label nil "gbut-create" "Implicit button text (with any delimiters): ")) (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect ...)) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char ...) (if ... nil ...) (hattr:set ... ... ...) (hattr:set ... ... src-dir) (hattr:set ... ... actype) (hattr:set ... ... ...) (hattr:set ... ... ...) (set-buffer but-buf) (setq lbl ...) (goto-char ...) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl))))) (if (eq start-buffer (current-buffer)) nil (error "Start buffer, '%s', differs from end buffer, '%s'" start-buffer (current-buffer))) (if (buffer-live-p start-buffer) nil (error "End buffer, '%s', is not live" (current-buffer)))))
  hui:gbut-create(nil nil)
  funcall-interactively(hui:gbut-create nil nil)
  call-interactively(hui:gbut-create)
  hui:menu-act(hyperbole nil nil nil)
  hyperbole(nil nil nil nil)
  funcall-interactively(hyperbole nil nil nil nil)
  command-execute(hyperbole)
```

It seems like it is trying to create HYPB on root.
I have tried to         
```
(setq hbmap:dir-user '("/Users/rsff/Dropbox/org/hyperbole/"))
(setq hbmap:dir-filename '("/Users/rsff/Dropbox/org/hyperbole/HBMAP"))

```
However, no sucess. :-)
I am assuming I´m doing something wrong...

**Comment by rswgnu** [comment]
For some reason your HYPB buffer is read-only.  Switch to it and do what the error says to do.  See if that fixes it.  Then we find out why this is happening for you.-- rswOn Jul 23, 2023, at 9:29 PM, fabinhorsff ***@***.***> wrote:﻿
I´m trying to create a global button and I am getting the following error:
Debugger entered--Lisp error: (error "(gbut-create) Read-only error in Hyperbole button buffer ’HYPB’.  Use {SPC t r} to enable edits.")
  error("(gbut-create) Read-only error in Hyperbole button buffer 'HYPB'.  Use {SPC t r} to enable edits.")
  hypb:error("(gbut-create) Read-only error in Hyperbole button buffer 'HYPB'.  Use {SPC t r} to enable edits.")
  (progn (pop-to-buffer but-buf) (hypb:error err))
  (if err (progn (pop-to-buffer but-buf) (hypb:error err)))
  (let (err) (save-current-buffer (set-buffer but-buf) (if buffer-read-only (progn (setq err (format "(%s) Read-only error in Hyperbole button buffer '%s'.  Use {%s} to enable edits." func-name (buffer-name but-buf) (hmouse-read-only-toggle-key)))))) (if err (progn (pop-to-buffer but-buf) (hypb:error err))))
  hui:buf-writable-err(#<buffer HYPB> "gbut-create")
  (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action (progn (hui:action actype)))) (set-buffer but-buf) (setq lbl (concat lbl (ebut:operate lbl nil))) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl))
  (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action (progn (hui:action actype)))) (set-buffer but-buf) (setq lbl (concat lbl (ebut:operate lbl nil))) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl)))
  (if ibut-flag (hui:gibut-create lbl (hui:hbut-label nil "gbut-create" "Implicit button text (with any delimiters): ")) (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action (progn (hui:action actype)))) (set-buffer but-buf) (setq lbl (concat lbl (ebut:operate lbl nil))) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl))))
  (progn (if ibut-flag (hui:gibut-create lbl (hui:hbut-label nil "gbut-create" "Implicit button text (with any delimiters): ")) (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action (progn ...))) (set-buffer but-buf) (setq lbl (concat lbl (ebut:operate lbl nil))) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl)))))
  (unwind-protect (progn (if ibut-flag (hui:gibut-create lbl (hui:hbut-label nil "gbut-create" "Implicit button text (with any delimiters): ")) (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect (gbut:file))) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char (point-max)) (if (bolp) nil (insert "\n")) (hattr:set 'hbut:current 'loc (hui:key-src but-buf)) (hattr:set 'hbut:current 'dir src-dir) (hattr:set 'hbut:current 'actype actype) (hattr:set 'hbut:current 'args (hargs:actype-get actype)) (hattr:set 'hbut:current 'action (if hui:ebut-prompt-for-action ...)) (set-buffer but-buf) (setq lbl (concat lbl ...)) (goto-char (point-max)) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl))))) (if (eq start-buffer (current-buffer)) nil (error "Start buffer, '%s', differs from end buffer, '%s'" start-buffer (current-buffer))) (if (buffer-live-p start-buffer) nil (error "End buffer, '%s', is not live" (current-buffer))))
  (let ((debug-on-error t) (start-buffer (current-buffer))) (if (buffer-live-p start-buffer) nil (error "Start buffer, '%s', is not live" (current-buffer))) (unwind-protect (progn (if ibut-flag (hui:gibut-create lbl (hui:hbut-label nil "gbut-create" "Implicit button text (with any delimiters): ")) (let (actype but-buf src-dir) (save-excursion (setq src-dir default-directory actype (hui:actype) but-buf (find-file-noselect ...)) (set-buffer but-buf) (hui:buf-writable-err (current-buffer) "gbut-create") (save-excursion (goto-char ...) (if ... nil ...) (hattr:set ... ... ...) (hattr:set ... ... src-dir) (hattr:set ... ... actype) (hattr:set ... ... ...) (hattr:set ... ... ...) (set-buffer but-buf) (setq lbl ...) (goto-char ...) (insert "\n") (save-buffer)) (message "`%s' global explicit button created." lbl))))) (if (eq start-buffer (current-buffer)) nil (error "Start buffer, '%s', differs from end buffer, '%s'" start-buffer (current-buffer))) (if (buffer-live-p start-buffer) nil (error "End buffer, '%s', is not live" (current-buffer)))))
  hui:gbut-create(nil nil)
  funcall-interactively(hui:gbut-create nil nil)
  call-interactively(hui:gbut-create)
  hui:menu-act(hyperbole nil nil nil)
  hyperbole(nil nil nil nil)
  funcall-interactively(hyperbole nil nil nil nil)
  command-execute(hyperbole)

It seems like it is trying to create HYPB on root.
I have tried to
(setq hbmap:dir-user '("/Users/rsff/Dropbox/org/hyperbole/"))
(setq hbmap:dir-filename '("/Users/rsff/Dropbox/org/hyperbole/HBMAP"))


However, no sucess. :-)
I am assuming I´m doing something wrong...

**Comment by fabinhorsff** [comment]
Yes! Thank you for the quick response! 

I tried the instructions - (in my case, {SPC t r}) But the file system is RO because it is trying to write to /HYPB, on the filesystem root.

When I removed the lines SETQ for hbmap:dir-user and hbmap:dir-filename from my config.el  it all worked perfectly. 

It seems Hyperbole it is not using these variables to determine where to create Global Buttons.

**Comment by rswgnu** [comment]
Where did the setq lines come from if you did not add them?If it works without those lines added to your config, is there a problem?We can have a look at whether Hyperbole is using those vars but it definitely gets its dir and filename from variables.  Irt could be a configuration issue.  For user configurable values, you should not use setq but something like configure-variable.-- rswOn Jul 24, 2023, at 3:58 PM, fabinhorsff ***@***.***> wrote:﻿
Yes! Thank you for the quick response!
I tried the instructions - (in my case, {SPC t r}) But the file system is RO because it is trying to write to /HYPB, on the filesystem root.
When I removed the lines SETQ for hbmap:dir-user and hbmap:dir-filename from my config.el  it all worked perfectly.
It seems Hyperbole it is not using these variables to determine where to create Global Buttons.

**Comment by fabinhorsff** [comment]
I am using Doom Emacs. 

In my config.el I have the following:

```
;; Setup Hyperbole!
(use-package! hyperbole
        :init  (hyperbole-mode 1)
        :config
        ;; (setq hbmap:dir-user '("/Users/rsff/Dropbox/org/hyperbole/"))
        ;; (setq hbmap:dir-filename '("/Users/rsff/Dropbox/org/hyperbole/HBMAP"))
        (setq hyrolo-kill-buffers-after-use t)
        (setq hyrolo-file-list '("~/Dropbox/org/roam/contatos.org"))
        (setq hyrolo-date-format "%Y-%m-%d")
        ) ;; end Hyperbole
```

I got a start in this config from a hyperbole talk in an Emacsconf that I saw here: https://emacsconf.org/2022/talks/rolodex/

I noticed that I did not communicate the error and my current setup. Sorry!
