### ISSUE TITLE
Poor performance for action/assist key outside of explicit buttons when `org-id-files` is large

### ISSUE THREAD

**Issue by vderyagin** [rswgnu/hyperbole#377]
Even in buffer containing only a single character, pressing action key takes multiple seconds before it says that no action is defined for this context. Pressing it on implicit buttons (like `gh#rswgnu/hyperbole`) is also slow.

Profiler output (partially excerpted below) says it's doing some org-id stuff, which doesn't seem like it should be happening. I got about 1000-long `org-id-files` list, so being slow is not surprising there.

Hyperbole version is fresh, 8.0.1pre.

```
       14217  87% - command-execute
       11138  68%  - call-interactively
        8646  53%   - funcall-interactively
        7551  46%    - hkey-either
        7551  46%     - action-key
        7551  46%      - action-key-internal
        7551  46%       - hkey-execute
        7551  46%        - eval
        7448  45%         - hbut:at-p
        7447  45%          - ibut:at-p
        7447  45%           - ibut:create
        7331  45%            - ibtypes::org-id
        7324  45%             - org-id-find
        7324  45%              - org-id-update-id-locations
        2883  17%               + abbreviate-file-name
        2240  13%               + insert-file-contents
        2010  12%               + mapcar
          54   0%               + org-entry-get
          45   0%               + org-at-property-p
          29   0%                 file-exists-p
          22   0%               + org-mode
          16   0%               + org-id-locations-save
          15   0%                 re-search-forward
           3   0%               + org-id-alist-to-hash
…
```

**Comment by vderyagin** [comment]
looks like this might be an org problem

**Comment by rswgnu** [comment]
Are you getting it corrected in Org?  Would like to prevent other people from experiencing this as Hyperbole’s. Ontext processing should always be sub-second by design.-- rswOn Aug 6, 2023, at 9:47 AM, Victor Deryagin ***@***.***> wrote:﻿
looks like this might be an org problem
