### ISSUE TITLE
Implement an implicit button

### ISSUE THREAD

**Issue by Sasanidas** [rswgnu/hyperbole#38]
I have this output from  xdebug(php debugger).
```
step_over
17 | step_over > break/ok
17 | file:///usr/Data_2/Programming/drupal-9.0.6/core/modules/views/src/DisplayPluginCollection.php:62
```

The path that is showed have a number in the end, delimited with : , that indicate the row of the file, but when I trigger the Implicit button, it doesn't take into the account the line number, it's just creates a new buffer with the full path, the dots and the number at the end.
My question is, what is the correct approach to this case, should I change the Implicit button action, create a new one or maybe change the button type.

Thank you.

**Comment by rswgnu** [comment]
You have found a bug.  Thank you.  We will work with it and resolve it.

**Comment by rswgnu** [comment]
This has been fixed in the current master branch here and will be in the next release.

**Comment by Sasanidas** [comment]
> This has been fixed in the current master branch here and will be in the next release.

Ok, that was quite fast, thank you!
