### ISSUE TITLE
I get the following error when trying to install hyperbole via elpa-devel:

### ISSUE THREAD

**Issue by Prague2049** [rswgnu/hyperbole#418]
describe-package-1: Wrong type argument: char-or-string-p, ("Bob Weiner" . "rsw@gnu.org")
mac,emacs-plus@29.1 , hyperbole-8.0.1pre0.20231210.205257

**Comment by rswgnu** [comment]
This is indeed a problem with the describe-package command which accepts
only a single Maintainer whereas Hyperbole has two.  It does allow for
multiple Authors.  For the next release, we have hopefully fixed this by
switching the writeup to have a single maintainer and multiple authors.

Thanks for pointing this out.  You don't get this when installing
Hyperbole, do you?  Only when using the help to describe the package, right?

**Comment by Prague2049** [comment]
Thanks for the reply. When I use M+x package-list-package, the above problem occurs when I hit enter on hyperbole.

**Comment by matsl** [comment]
@rswgnu 
> This is indeed a problem with the describe-package command which accepts only a single Maintainer

That does not seem to be the case. There is even code in describe-package-1 to display "Maintainers" with an s. https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/emacs-lisp/package.el#n2962 just as Authors can be more than one.

So we need to figure out why this happens. Could be a bug in package.el when getting the names or we provide it in the wrong way!? I see other packages affected by this as well. Would be terrible if we could not display both our names wouldn't it! ;-)

**Comment by rswgnu** [comment]
If you look at Emacs 28.0.50, you’ll see single maintainer code that they must have extended along the way.  — Bob-- BobOn Dec 22, 2023, at 9:17 AM, Mats Lidell ***@***.***> wrote:﻿
@rswgnu

This is indeed a problem with the describe-package command which accepts only a single Maintainer

That does not seem to be the case. There is even code in describe-package-1 to display "Maintainers" with an s. https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/emacs-lisp/package.el#n2962 just as Authors can be more than one.
So we need to figure out why this happens. Could be a bug in package.el when getting the names or we provide it in the wrong way!? I see other packages affected by this as well. Would be terrible if we could not display both our names wouldn't it! ;-)

**Comment by matsl** [comment]
FYI: I do get the error in still in emacs 30.0.5.  The "fix" for allowing multiple Maintainers is here: [bug#62524](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62524) It speak of a new :maintainers: extra property. Maybe that is what we need to support.

**Comment by rswgnu** [comment]
Ok, I’ll add a Maintainers line to hyperbole.el as well.-- BobOn Dec 22, 2023, at 1:16 PM, Mats Lidell ***@***.***> wrote:﻿
FYI: I do get the error in still in emacs 30.0.5.  The "fix" for allowing multiple Maintainers is here: bug#62524 It speak of a new :maintainers: extra property. Maybe that is what we need to support.

**Comment by rswgnu** [comment]
This was fixed in the 8.0.1pre release a while back.  Closing this issue.
