### ISSUE TITLE
Installing hyperbole via straight package manager fails

### ISSUE THREAD

**Issue by infoparticle** [rswgnu/hyperbole#42]
Please refer: https://github.com/raxod502/straight.el/issues/623

I tried installing hyperbole via straight.
The package got properly cloned but the compile and build step fails moving some of the required directories to straight\build\hyperbole.

straight\repos\hyperbole\kotl should be in the straight\build\hyperbole too. This missing kotl directory breaks the installation.

It could be the mistake of hyperbole package, may be it's following non-standard way of packaging its folders/files.

**Comment by rswgnu** [comment]
On Sat, Oct 31, 2020 at 11:55 PM Gopi <notifications@github.com> wrote:

> Please refer: raxod502/straight.el#623
> <https://github.com/raxod502/straight.el/issues/623>
>

Yes, as portfolio noted in the above link, you have to add the kotl
subdirectory to your straight recipe so that all the files are compiled
properly.

**Comment by infoparticle** [comment]
Thanks for your help!
