### ISSUE TITLE
Can Koutline support narrowing functionality?

### ISSUE THREAD

**Issue by 101scholar** [rswgnu/hyperbole#456]
When content grows, screen filled with words can be distracting. Is it possible to add a org-narrow analog in Koutline?

**Comment by rswgnu** [comment]
Hard to see how this would be useful given that you can immediately move any cell or tree to any other part of the outline.  If you just want to narrow to one cell of text, you could do that now but when you unnarrow, you may expose internal Koutline data.  Instead, think about just collapsing trees you don't want to see at any moment.
