### ISSUE TITLE
When hyperbole-mode is re-enabled, kotl-mode is not loaded

### ISSUE THREAD

**Issue by 101scholar** [rswgnu/hyperbole#457]
If I config hyperbole the following way

```lisp
(use-package hyperbole
  :custom
  (hyperbole-mode nil))
```

Then when I manually enable hyperbole-mode by M-x, functions like kotl-mode is not loaded.

**Comment by 101scholar** [comment]
A quick fix is

```lisp
(use-package hyperbole
  :config
  (hyperbole-mode -1)
  (hyperb:init))
```

But I think it is a bug to require user to explicitly call `(hyperb:init)`.

Moreover, the reason that I want to disable hyperbole-mode is that this minor-mode's keymap conflicts with my global keymap. So is it possible that this package provide a customized prefix for hyperbole-mode-map? Currently, there's no such prefix and it is easy to conflict with user's own key bindings.

**Comment by rswgnu** [comment]
You should be able to rebind C-h h to your own keymap as you normally would, after initializing Hyperbole.-- rswOn Jan 26, 2024, at 7:09 AM, 101scholar ***@***.***> wrote:﻿
A quick fix is
(use-package hyperbole
  :config
  (hyperbole-mode -1)
  (hyperb:init))
But I think it is a bug to require user to explicitly call (hyperb:init).
Moreover, the reason that I want to disable hyperbole-mode is that this minor-mode's keymap conflicts with my global keymap. So is it possible that this package provide a customized prefix for hyperbole-mode-map? Currently, there's no such prefix and it is easy to conflict with user's own key bindings.

**Comment by 101scholar** [comment]
I mean for example currently the package binds `M-o` to hkey-operate in hyperbole-mode-map, it's better to add some customized prefix so that it won't mess up keybinding of other packages.

**Comment by rswgnu** [comment]
M-o is bound by Hyperbole only if it has the default global Emacs binding of 'facemenu-keymap' or if it has not been bound to something else by the user.  So just set your personal binding before initializing Hyperbole and you should be fine.

**Comment by rswgnu** [comment]
101scholar wrote:

> If I config hyperbole the following way
> 
> ```lisp
> (use-package hyperbole
>   :custom
>   (hyperbole-mode nil))
> ```
> 
> Then when I manually enable hyperbole-mode by M-x, functions like kotl-mode is not loaded.

This is something that should be resolved if you are running the Hyperbole pre-release V8.0.1pre from the elpa-devel archive.  You can see code to fix it at the bottom of hyperbole.el.
