### ISSUE TITLE
Org files have HyRoloOrg as major-mode after adding them to the hyrolo-file-list

### ISSUE THREAD

**Issue by ronspe** [rswgnu/hyperbole#487]
Hi,

I added all my .org files to the hyrolo-file-list like this:
`(setq hyrolo-file-list (cons "~/.emacs.d/hyperb/rolo.otl" (cddr (directory-files-recursively ORGDIR "\\.org$"))))`
("ORGDIR" is a variable)
This works as expected, but now when I open one of these .org files, they no longer have the org-mode major mode but they have HyRoloOrg as major mode so I lost all normal formatting. I have to invoke M-x org-mode to bring the formatting back.
I'm using Hyperbole 9.0.1

How can I keep the org-mode for these files? 
Thanks, Ronald.

**Comment by ronspe** [comment]
Hi,
Sorry for the inconvenience, but somehow the issue resolved itself.

Thanks, Ronald.

**Comment by ronspe** [comment]
Hi,
It looked like the problem solved itself, but it did not...
The problem only occurs **after** I have run a HyRolo WordFind. Only after the search, the major mode is changed for the files that are in the hyrolo-file-list. The org files that are not in the hyrolo-file-list are not affected.
![2024-03-14_10-50-hyrolo](https://github.com/rswgnu/hyperbole/assets/44189214/6414c9cb-81b0-43ef-9feb-2f128c39ea39)

Thanks, Ronald.

**Comment by rswgnu** [comment]
Hi Ronald:

You are right.  This is an optimization to make loading Org files much faster.  If you press {e} to edit one of the matches in the HyRolo buffer, you’ll find it switches to normal Org mode for editing.

We neglected to think about switching to the buffers searched in other ways.  We’ll have to add a buffer switch hook to enable the normal Org mode.  Thanks for pointing this out.

-- rsw

**Comment by rswgnu** [comment]
This has fixed in the latest Hyperbole pre-release, 8.0.2pre available from the elpa-devel archive as a package.
