### ISSUE TITLE
Is it possible for hyperbole to create links to words in the org-mode?

### ISSUE THREAD

**Issue by Odysseus6000** [rswgnu/hyperbole#491]
Is it possible for hyperbole to create links it can link to words with plain text content in the org-mode file?
The new explicit link button created with {C-h h e l} links to a location in the org-mode file. The way it creates a link between two windows is very convenient and can be used with ace-window. These are amazing.If the file is modified and this location is moved, it won't link to the original location of the text? The rules of org-mode require the addition of <<Tagret>> to link to the text content, and the need to keep <<Tagret>> unique.
Another way is to create an ID attribute for the headline. But for a paragraph, splitting the headline will destroy the original content.

**Comment by Odysseus6000** [comment]
For example: 
* Test1
    ...
    There are many important cases for companies in this situation. 
     ...

Below that there is a headline labeled Test1, and below it is a paragraph of text... indicates that some of the plain text content has been omitted. I want to link to the important case these words . If I use the implicit button link the link is formed as follows
"~/file.org:100:25"
The position of "important case" is 100:25. i don't want to set the line where the important case is located as headline. is there any other way to link to important case and still link to it when the position of the paragraph where these words are located changes.?

**Comment by rswgnu** [comment]
Manually, you can just type the implicit link like so:“~/file.org#important cases”We will have to think about how this case could be automated.— rswOn Mar 20, 2024, at 12:57 AM, Odysseus6000 ***@***.***> wrote:﻿
For example:

Test1
...
There are many important cases for companies in this situation.
...

Below that there is a headline labeled Test1, and below it is a paragraph of text... indicates that some of the plain text content has been omitted. I want to link to the important case these words . If I use the implicit button link the link is formed as follows
"~/file.org:100:25"
The position of "important case" is 100:25. i don't want to set the line where the important case is located as headline. is there any other way to link to important case and still link to it when the position of the paragraph where these words are located changes.?

**Comment by matsl** [comment]
@rswgnu 
> We will have to think about how this case could be automated.

Would it make sense if we create a string match link if the "target" buffer region is active?

**Comment by rswgnu** [comment]
Mats suggestion above has been added to the latest Hyperbole pre-release, 8.0.2pre, available now from elpa-devel.  Simply select the region of text you want to link to (must be a single line) in the referent target buffer, then switch to the source buffer where the link button should go and press {C-h h i l} and a link to the instance of the string you have selected will be inserted.
