### ISSUE TITLE
Get hyperbole action key to recognize org =verbatim= text?

### ISSUE THREAD

**Issue by matogoro** [rswgnu/hyperbole#503]
Hi,

I often use `org-mode`'s `=verbatim=` markdown when mentioning filenames in org files, which is useful for text highlighting purposes when I read these files later.  I was also able to get hyperbole to recognize these file paths with the action key (`M-RET`) by defining custom delimiters using the `defil` macro as follows:

`(defil hy-verbatim-find-file "=" "=" ".*" "\\&")`

However, this doesn't seem to be working anymore---when I try pressing an action key on a verbatim filename (e.g., `=~/test.txt=`), I get an error (debug below):

```
Debugger entered--Lisp error: (error "(ibut:to-text): ’lbl-key’ arg must be a string, not: nil")
  error("(ibut:to-text): 'lbl-key' arg must be a string, not: %S" nil)
  (if (stringp lbl-key) nil (error "(ibut:to-text): 'lbl-key' arg must be a string, not: %S" lbl-key))
  ibut:to-text(nil)
  hui:hbut-operate(hbut:act "Activate Hyperbole button: " hbut:current)
  hui:hbut-act(hbut:current)
  hkey-execute(nil)
  action-key-internal()
  action-key()
  hkey-either(nil)
  funcall-interactively(hkey-either nil)
  command-execute(hkey-either)
```

Notably, when trying to use the action key (`M-RET`) on filenames without delimiters, the action key works correctly.  Moreover, when I use different custom delimiters (e.g., `(defil hy-verbatim-find-file "{{" "}}" ".*" "\\&")` --> `{{~/test.txt}})`, the action key also works correctly---so maybe it's something intrinsically wrong with using `=` as a delimiter?

It there some way to reconcile this?  Any help would be greatly appreciated!

**Comment by rswgnu** [comment]
Hi:

This is a bug that you have found.  It should be fixed soon and we'll
report back here.  Thanks for finding it.  -- rsw

**Comment by rswgnu** [comment]
This bug is now resolved in the Hyperbole source archive at Github.  It
will be available for download from melpa or elpa-devel within the next 12
hours.  If you just update your hbut.el file manually, that is all you need
to do if you are in a hurry.  -- rsw

**Comment by matogoro** [comment]
Just tested it—works perfectly!  Thank you for your amazingly fast response and your help.

**Comment by rswgnu** [comment]
Great, emjoy and keep building implicit button types to simplify your work.
