### ISSUE TITLE
Infinite loop/hang when formatting/browsing some C/C++ code/headers

### ISSUE THREAD

**Issue by pillowtrucker** [rswgnu/hyperbole#518]
Hello,
As in the subject, I've encountered a few scenarios where it seems that hyperbole is introducing an infinite loop and hanging emacs.
I initially thought it was an lsp-bug, then was asked to send a bug to emacs itself because on the surface it looked like a cc-mode bug. I finally found the source of the weird regex and t seems that the package hooking that cc-mode callback with the regular expression is actually hyperbole in here https://github.com/rswgnu/hyperbole/blob/master/hui-select.el#L404

My original report to lsp-mode: https://github.com/emacs-lsp/lsp-mode/issues/1621#issuecomment-2058599614

My bug report to the emacs mailing list read as follows:

Among other scenarios, when clang-format runs as a hook on file save when I make any (even noop) edit in https://github.com/pillowtrucker/mir/blob/main/src/platform/graphics/drm_formats.cpp this file, for example, emacs enters an infinite loop consuming 100% of a cpu core and all memory up to gc threshold.
It is not always the regex function on the top of the stack but it is always a call around those functions
"beginning-of-defun-raw"
"beginning-of-defun"
"c-get-fallback-scan-pos"

GDB trace: https://gist.github.com/pillowtrucker/cf61381dd95c18f72e4c7ab8df32039a

This is not the only scenario when this happens. I can also sometimes trigger the same thing by trying to jump to the definition of a symbol from a .cpp/c++-header file into a system header (all of which are on a read-only filesystem on my computer), for example one of the SDL headers. The main difference is that the buffer-switching gets mixed into the lot and emacs doesn't even respond to C-g and I have to kill -SIGUSR2 it to get it to start responding again, but I'm pretty sure it's the same bug - output from this scenario is here: https://gist.github.com/pillowtrucker/a15c4c825a9e72cde8f2a286db16b070

I'm sorry about the <optimized out> everywhere and lack of inlined sources, but I've already rebuilt it with nixos's enableDebugging flag, which should have enabled -Og and -g3 (I think it did do the latter but failed on the optimizations and left it at O2) and I've already spent most of my day debugging this and it would take another full day to figure out how to properly override the byzantine nixpkgs emacs infrastructure with the right optimization flag and to store the right source tree.

System info from emacs: https://gist.github.com/pillowtrucker/c93d0e9114ce11cddc48dc254b5bdbd9

**Comment by rswgnu** [comment]
Hi Mauritius:

Sorry you ran into this.  I took a look back in our Hyperbole and Emacs
discussion archives and found a long conversation connected to Emacs
bug#61436 that points to the same problem.  After a lot of discussion, Alan
Mackenzie ended up fixing one issue in the Emacs regexp handler and redoing
Hyperbole's Java defun regexp but things went on so long that we forgot
about the original C++ regexp and that never got rewritten.

I have asked Alan to work on the C++ regexp.  In the meantime, we can
disable this behavior in C++ to prevent other people from tripping over it.

Regards,

-- rsw

**Comment by rswgnu** [comment]
Great.

**Comment by pillowtrucker** [comment]
Based on that other thread, am I understanding correctly that there already is a fix on the C-language/emacs side of things, but it's only in git/unrealeased version 30 ?

**Comment by rswgnu** [comment]
We have fixed the Hyperbole part if you get the latest elpa-devel or melpa release.  The cc-mode.el would be in the pre-release of Emacs.  I am closing this issue now; thanks for reporting it.
