### ISSUE TITLE
Change in `defib` behavior

### ISSUE THREAD

**Issue by ctechols** [rswgnu/hyperbole#527]
I have some implicit buttons defined with `defib` that do not seem to work as they used to.  I now have to wrap the button text in delimiters like `<>` to get the button to work without error.

Here is an example `defib`:

```
  (defib hyperbole-issue ()
    "Search for issues with hyperbole on github"
    (cond
     ((thing-at-point-looking-at "hypiss:\\([0-9]+\\)")
      (let ((iss-id (match-string-no-properties 1)))
	(hact 'www-url (concat "https://github.com/rswgnu/hyperbole/issues/" iss-id))))))
```

Before the 9.0 release this used to successfully open the browser with the bare text (`hypiss:522`).  Now I get the following error message if I put point on the text and run `hkey-either`:
```
if: (ibut:to-text): ’lbl-key’ arg must be a string, not: nil
```

If I run `hkey-help` when point is on the text:
```
<snip>
hyperbole-issue IMPLICIT BUTTON SPECIFICS:
   actype:          www-url
   loc:             #<buffer *scratch*>
   dir:             "~/"
   categ:           ibtypes::hyperbole-issue
   args:            ("https://github.com/rswgnu/hyperbole/issues/522")

  Search for issues with hyperbole on github
<snip>
```

If I use delimiters around the text (`<hypiss:522>`) and run `hkey-either` my browser will open the URL.  Also the output of `hkey-help` is different:
```
<snip>
hyperbole-issue IMPLICIT BUTTON SPECIFICS:
   categ:           ibtypes::hyperbole-issue
   lbl-key:         "hypiss:522"
   lbl-start:       155
   lbl-end:         167
   actype:          www-url
   loc:             #<buffer *scratch*>
   dir:             "~/"
   args:            ("https://github.com/rswgnu/hyperbole/issues/522")

  Search for issues with hyperbole on github
<snip>
```

Particularly, there are values for the `lbl-*` fields, which seems relevant to the error message.

**Comment by matsl** [comment]
Hi @ctechols, 

Thanks for the report. The defib definition looks fine to me so will take a look.

**Comment by matsl** [comment]
Hi @ctechols, 

I'm sorry but there is a backward incompatibility. You now need to explicitly set the lbl-key. Before calling `hact` set the label using a call like this (that makes the whole string the label):

```
(ibut:label-set (match-string-no-properties 0) (match-beginning 0) (match-end 0))
``` 

With this your defib's should work as before.

**Comment by ctechols** [comment]
@matsl I can confirm that this fixes my issue.

Thank you for investigating!
