### ISSUE TITLE
Can't use `org-meta-return` in org buffer even after configuring

### ISSUE THREAD

**Issue by edenworky** [rswgnu/hyperbole#603]
I tried using `C-h h c o`, but none of the available options (including "None") disables the default `M-RET` in org buffers, i.e. still doesn't create a new heading when invoked at the end of a line.

**Comment by matsl** [comment]
Hi @edenworky Thanks for the report. I can recreate the described behavior. Looking into it. :pray:

**Comment by matsl** [comment]
Hi @edenworky With #607 `None` and `Hyperbole-Buttons-Only` should give you the desired behavior. With `All-Hyperbole-Contexts` smart-eolp behavior will be active. _(In the later case you will still get the org behavior if at the last line of a file but I'm looking into closing that gap.)_

**Comment by rswgnu** [comment]
Hi @edenworky:

I'm pretty sure this is resolved as of today with commit #a7aefb122.  Hyperbole's end-of-line behavior should now defer to Org-mode when the config option is set to None, meaning Hyperbole's M-RET control is never active or if set to :buttons, meaning it is active only when on text Hyperbole recognizes as a hyperbutton.  Additionally, we have improved end-of-buffer handling to be consistent with end-of-line handling so on the last line of the buffer if there is any non-whitespace text, behavior will match that of any other line.

Get the latest from melpa or elpa-devel and let us know after restarting your Emacs if it works as you expect and then we'll close this issue.
