### ISSUE TITLE
Errors when choosing action type: exec-kbd-macro

### ISSUE THREAD

**Issue by DynamicMetaFlow** [rswgnu/hyperbole#9]
Greetings,

First, thank you for creating hyperbole. I've had the time recently to use it, and I'm trying to incorporate it into my workflow for my information management system to reduce cognitive load. I'm enjoying the experience and looking forward to using it.

**Use case:**
One use-case I'm imagining is to have in my button file, buttons that execute a keyboard macro that searches for information across different locations/contexts.

**Problem:**
I've created a button in my button file, and the action type that I select is exec-kbd-macro.
The errors I'm getting are:

`load: Cannot open load file: No such file or directory, treemacs-interface.el
`

After troubleshooting, I installed treemacs and then was running into other errors related to vm-autoloads, and w3. 

I'm unsure of what next steps to take and was wondering if you could shed some light on this issue. I'm running emacs 27.0.50, with a new barebones .emacs.d configuration and installed hyperbole from the example given.

```
(require 'package)
(setq package-enable-at-startup nil) ;; Prevent double loading of libraries
(package-initialize)
(unless (package-installed-p 'hyperbole)
  (package-refresh-contents)
  (package-install 'hyperbole))
(require 'hyperbole)

```

Thank you for your time and continued support.

**Comment by rswgnu** [comment]
Hi Alex:

Welcome and thanks for your very clear issue submission.

> Greetings,
> 
> First, thank you for creating hyperbole. I've had the time recently to use it, and I'm trying to incorporate it into my workflow for my information management system to reduce cognitive load. I'm enjoying the experience and looking forward to using it.

Great, let us know if we can help.

> **Use case:**
> One use-case I'm imagining is to have in my button file, buttons that execute a keyboard macro that searches for information across different locations/contexts.
> **Problem:**
> I've created a button in my button file, and the action type that I select is exec-kbd-macro.
> The errors I'm getting are:
> 
> `load: Cannot open load file: No such file or directory, treemacs-interface.el `

Unless, you are trying to use treemacs in your keyboard macro, Hyperbole should not load anything from treemacs.  If it does, this is an error we should fix.  Use the 'format-kbd-macro' function to output your macro and include it here so we can potentially duplicate the behavior.

> After troubleshooting, I installed treemacs and then was running into other errors related to vm-autoloads, and w3.

Again, these packages should not be required unless used.  Some autoloads may be utilized but any such ones should be part of your installation.  You can also install Hyperbole through the Emacs package manager like any other package now.

> I'm unsure of what next steps to take and was wondering if you could shed some light on this issue. I'm running emacs 27.0.50, with a new barebones .emacs.d configuration and installed hyperbole from the example given.

Give us steps to replicate this and we should be able to resolve it fairly quickly.

**Comment by DynamicMetaFlow** [comment]
> Again, these packages should not be required unless used. Some autoloads may be utilized but any such ones should be part of your installation. You can also install Hyperbole through the Emacs package manager like any other package now.
>

Hi Robert,

Thank you for your reply and willingness to help, it's appreciated. After reading your reply I decided to take a closer look at my installation to see why are these packages not loading. 

After I bisected my emacs configuration file I found out the additional loading of packages was related to [Helm](https://github.com/emacs-helm/helm). After I commented out the helm package the problems are no longer present.

I'm going to look into seeing if I can configure helm in such a way so that it doesn't conflict with Hyperbole.

Thank you for your support and assistance in this process.

Best,
Alex

**Comment by rswgnu** [comment]
I use Helm with Hyperbole but I had to heavily modify parts so they would work compatibly.  It is not easy to imtegrate with other packages like Hyperbole.  The maintainer did not accept the changes although they made various improvements.

-- Bob

**Comment by DynamicMetaFlow** [comment]
> I use Helm with Hyperbole but I had to heavily modify parts so they would work compatibly. It is not easy to imtegrate with other packages like Hyperbole. The maintainer did not accept the changes although they made various improvements.
> […](#)
> -- Bob

Thank you for the update, are the parts you modified with Helm available? 

One workaround solution I'm thinking about is creating a function that disables Helm and then launches the Hyperbole Menu and re-enables Helm afterwards. Could maybe use add-advice, :before :after at least in this way there wouldn't be any unexpected errors coming up.

**Comment by rswgnu** [comment]
Yes, see: https://github.com/rswgnu/helm

If there is a problem, it would help if you could submit a minimal example.  Load helm and demonstrate that treemacs and vm do not load. 

Then load Hyperbole and show a keyboard macro button that when activated triggers the problem.

**Comment by rswgnu** [comment]
Yes, see: https://github.com/rswgnu/helm

If there is a problem, it would help if you could submit a minimal example.  Load helm and demonstrate that treemacs and vm do not load. 

Then load Hyperbole and show a keyboard macro button that when activated triggers the problem.

**Comment by rswgnu** [comment]
Did you get my version of helm working with your Hyperbole installation?

**Comment by DynamicMetaFlow** [comment]
> Did you get my version of helm working with your Hyperbole installation?

Hi, thank you for the link to your version of Helm. I haven't had the opportunity to try it out. I will try it on the weekend. 

The cases of where Helm and Hyperbole interfere are small enough that it doesn't impact my usage on the day to day and if it occurs I could disable helm mode temporarily when using Hyperbole. 

Thank you again for creating Hyperbole! I'm only beginning to scratch the surface and I'm happy and impressed by how easy it's been to integrate to my workflow!

![2019-05-01-210823_641x336_scrot](https://user-images.githubusercontent.com/10332647/57052436-144b2600-6c55-11e9-8597-52c83100dd25.png)

**Comment by rswgnu** [comment]
> On May 1, 2019, at 9:07 PM, Alex <notifications@github.com> wrote:
> Thank you again for creating Hyperbole! I'm only beginning to scratch the surface and I'm happy and impressed by how easy it's been to integrate to my workflow!
> 

Great, consider joining the low traffic Huperbole mailing list.  — Bob
